-- ===========================================================================
-- V10__newsletter.sql
-- Plan v2 §4.8 — Suscripciones a newsletter con double opt-in.
--
-- Flow:
--   1. Usuario rellena form en footer con su email → POST /api/newsletter.
--   2. Backend genera token UUID, persiste fila con confirmado=false +
--      expira_en=now+48h, envía email Resend con link /newsletter/confirmar?token=XXX.
--   3. Usuario click → GET /api/newsletter/confirmar?token=XXX marca
--      confirmado=true y limpia el token (one-shot).
--   4. Unsubscribe vía POST /api/newsletter/unsubscribe { email, token } —
--      el token de unsubscribe va en el footer de cada envío real (futuro
--      Bloque 8.6 cuando montemos la newsletter automatizada).
--
-- Diseño:
--   - email es UNIQUE: no permitimos múltiples subs del mismo correo.
--     Si reintentan suscribirse: refresh del token y reenvio del email
--     de confirmación (en lugar de error 409 al user — UX).
--   - token de confirmación es UUID 36 chars. Tras confirmar pasa a NULL
--     para que no se pueda reusar.
--   - token_unsubscribe (segundo token) persistente para enlazar desde
--     el footer de los emails enviados. Diferente del de confirmación
--     porque tiene ciclo de vida distinto (uno expira, otro vive mientras
--     la suscripción esté activa).
-- ===========================================================================

CREATE TABLE newsletter_subs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL,
    confirmado          BOOLEAN      NOT NULL DEFAULT FALSE,
    token_confirm       VARCHAR(64),
    token_unsubscribe   VARCHAR(64)  NOT NULL,
    confirm_expira_en   TIMESTAMP,
    fecha_alta          TIMESTAMP    NOT NULL,
    fecha_confirmacion  TIMESTAMP,
    CONSTRAINT uk_newsletter_email UNIQUE (email)
);

CREATE INDEX idx_newsletter_email             ON newsletter_subs (email);
CREATE INDEX idx_newsletter_token_confirm     ON newsletter_subs (token_confirm);
CREATE INDEX idx_newsletter_token_unsubscribe ON newsletter_subs (token_unsubscribe);
