-- ===========================================================================
-- V1__initial_schema.sql
-- Plan v2 §2.7 — baseline de Flyway. Snapshot del schema completo tal como
-- vive en producción tras todas las migraciones manuales que aplicaba
-- SchemaMigrations.java (rename enum, slug, ronda, refresh tokens, etc).
--
-- En BBDDs nuevas (dev, tests, instancias frescas): este script crea las
-- 7 tablas desde cero.
--
-- En BBDDs existentes (Neon en prod): NO se ejecuta. Flyway lo marca como
-- aplicado vía baseline-on-migrate=true al detectar tablas previas. Las
-- siguientes migraciones (V2..Vn) sí correrán secuencialmente.
--
-- Convenciones:
--   - SQL portable Postgres + H2 (MODE=PostgreSQL para tests).
--   - Identidades: BIGINT GENERATED BY DEFAULT AS IDENTITY (estándar SQL,
--     soportado por ambos motores; evita SERIAL específico de Postgres).
--   - Sin ON DELETE explícito → default RESTRICT. Las cascadas las hace
--     DataSeeder con queries explícitas (más auditable que cascade).
--   - snake_case en columnas (alineado con SpringPhysicalNamingStrategy).
-- ===========================================================================


-- usuarios -----------------------------------------------------------------
CREATE TABLE usuarios (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    avatar_url         TEXT,
    rol                VARCHAR(20)  NOT NULL,
    fecha_registro     TIMESTAMP    NOT NULL,
    intentos_fallidos  INTEGER      NOT NULL DEFAULT 0,
    bloqueado_hasta    TIMESTAMP,
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT uk_usuarios_email    UNIQUE (email)
);
CREATE INDEX idx_usuarios_email    ON usuarios (email);
CREATE INDEX idx_usuarios_username ON usuarios (username);


-- personajes ---------------------------------------------------------------
CREATE TABLE personajes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(255) NOT NULL,
    nombre       VARCHAR(255) NOT NULL,
    anime        VARCHAR(255) NOT NULL,
    descripcion  VARCHAR(500),
    imagen_url   VARCHAR(500),
    CONSTRAINT uk_personajes_slug UNIQUE (slug)
);
CREATE INDEX idx_personajes_slug  ON personajes (slug);
CREATE INDEX idx_personajes_anime ON personajes (anime);


-- torneos ------------------------------------------------------------------
CREATE TABLE torneos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                  VARCHAR(80),
    nombre                VARCHAR(255) NOT NULL,
    descripcion           VARCHAR(500),
    estado                VARCHAR(20)  NOT NULL,
    fecha_creacion        TIMESTAMP,
    fecha_inicio          TIMESTAMP,
    fecha_finalizacion    TIMESTAMP,
    ganador_personaje_id  BIGINT,
    CONSTRAINT uk_torneos_slug UNIQUE (slug),
    CONSTRAINT fk_torneo_ganador
        FOREIGN KEY (ganador_personaje_id) REFERENCES personajes (id)
);


-- enfrentamientos ----------------------------------------------------------
CREATE TABLE enfrentamientos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id       BIGINT  NOT NULL,
    personaje1_id   BIGINT,
    personaje2_id   BIGINT,
    ganador_id      BIGINT,
    ronda           INTEGER NOT NULL DEFAULT 1,
    fecha_creacion  TIMESTAMP NOT NULL,
    CONSTRAINT fk_enf_torneo
        FOREIGN KEY (torneo_id)     REFERENCES torneos    (id),
    CONSTRAINT fk_enf_personaje1
        FOREIGN KEY (personaje1_id) REFERENCES personajes (id),
    CONSTRAINT fk_enf_personaje2
        FOREIGN KEY (personaje2_id) REFERENCES personajes (id),
    CONSTRAINT fk_enf_ganador
        FOREIGN KEY (ganador_id)    REFERENCES personajes (id)
);
CREATE INDEX idx_enf_torneo       ON enfrentamientos (torneo_id);
CREATE INDEX idx_enf_personaje1   ON enfrentamientos (personaje1_id);
CREATE INDEX idx_enf_personaje2   ON enfrentamientos (personaje2_id);
CREATE INDEX idx_enf_torneo_ronda ON enfrentamientos (torneo_id, ronda);


-- votos --------------------------------------------------------------------
CREATE TABLE votos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha              TIMESTAMP NOT NULL,
    personaje_id       BIGINT    NOT NULL,
    usuario_id         BIGINT,
    enfrentamiento_id  BIGINT,
    CONSTRAINT fk_voto_personaje
        FOREIGN KEY (personaje_id)      REFERENCES personajes      (id),
    CONSTRAINT fk_voto_usuario
        FOREIGN KEY (usuario_id)        REFERENCES usuarios        (id),
    CONSTRAINT fk_voto_enfrentamiento
        FOREIGN KEY (enfrentamiento_id) REFERENCES enfrentamientos (id),
    CONSTRAINT uk_voto_personaje_usuario
        UNIQUE (personaje_id, usuario_id),
    CONSTRAINT uk_voto_enfrentamiento_usuario
        UNIQUE (enfrentamiento_id, usuario_id)
);
CREATE INDEX idx_votos_personaje      ON votos (personaje_id);
CREATE INDEX idx_votos_enfrentamiento ON votos (enfrentamiento_id);


-- refresh_tokens (Plan v2 §1.3) --------------------------------------------
CREATE TABLE refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT       NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL,
    creado_en    TIMESTAMP    NOT NULL,
    expira_en    TIMESTAMP    NOT NULL,
    revocado_en  TIMESTAMP,
    user_agent   VARCHAR(500),
    ip_addr      VARCHAR(64),
    CONSTRAINT uk_refresh_tokenhash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
CREATE INDEX idx_refresh_tokenhash ON refresh_tokens (token_hash);
CREATE INDEX idx_refresh_usuario   ON refresh_tokens (usuario_id);
CREATE INDEX idx_refresh_expira    ON refresh_tokens (expira_en);


-- password_reset_tokens ----------------------------------------------------
-- Sin FK explícita a usuarios (decisión legacy: el código maneja la
-- referencia por id sin garantizar integridad referencial). Si llegara a
-- borrarse un usuario con tokens activos, las filas quedarían huérfanas
-- pero inofensivas. Refactor a FK queda pendiente de Bloque 2 futuro.
CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    codigo      VARCHAR(6)   NOT NULL,
    expira_en   TIMESTAMP    NOT NULL,
    creado_en   TIMESTAMP    NOT NULL,
    usado       BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_prt_usuario_codigo ON password_reset_tokens (usuario_id, codigo);
