-- Comentarios moderados en fichas de personaje.
-- Nueva migración: no se toca ninguna V1..V20 ya aplicada en producción.

CREATE TABLE comentarios_personaje (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor_id        BIGINT       NOT NULL,
    personaje_slug  VARCHAR(120) NOT NULL,
    contenido       TEXT         NOT NULL,
    estado          VARCHAR(32)  NOT NULL DEFAULT 'VISIBLE',
    reportes        INTEGER      NOT NULL DEFAULT 0,
    creado_en       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentarios_autor
        FOREIGN KEY (autor_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_comentarios_personaje_slug
        FOREIGN KEY (personaje_slug) REFERENCES personajes (slug) ON DELETE CASCADE,
    CONSTRAINT ck_comentarios_estado
        CHECK (estado IN ('VISIBLE', 'PENDIENTE_REVISION', 'OCULTO', 'ELIMINADO'))
);

CREATE INDEX idx_comentarios_personaje_estado_fecha
    ON comentarios_personaje (personaje_slug, estado, creado_en DESC);

CREATE INDEX idx_comentarios_autor_fecha
    ON comentarios_personaje (autor_id, creado_en DESC);

CREATE INDEX idx_comentarios_estado_fecha
    ON comentarios_personaje (estado, creado_en DESC);
