-- Estado publico de disponibilidad de AnimeShowdown.
-- Registra una muestra por minuto desde el scheduler del backend y mantiene
-- el dashboard /status alimentado por datos persistidos, no por memoria.

CREATE TABLE uptime_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checked_at  TIMESTAMP NOT NULL,
    status      VARCHAR(16) NOT NULL,
    latency_ms  BIGINT NOT NULL,
    detail      VARCHAR(255)
);

CREATE INDEX idx_uptime_log_checked_at ON uptime_log (checked_at);
CREATE INDEX idx_uptime_log_status_checked_at ON uptime_log (status, checked_at);
