-- Logro social "Madrugador": primera persona que vota a un personaje en el
-- dia UTC. La unicidad vive en BBDD para resolver carreras entre dos votos
-- simultaneos sin depender de locks de aplicacion.

CREATE TABLE madrugadores_dia (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_slug   VARCHAR(255) NOT NULL,
    fecha            DATE NOT NULL,
    primer_user_id   BIGINT NOT NULL,
    hora             TIMESTAMP NOT NULL,
    CONSTRAINT fk_madrugadores_usuario
        FOREIGN KEY (primer_user_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_madrugadores_personaje_fecha UNIQUE (personaje_slug, fecha)
);

CREATE INDEX idx_madrugadores_usuario_fecha ON madrugadores_dia (primer_user_id, fecha DESC);
CREATE INDEX idx_madrugadores_personaje_fecha ON madrugadores_dia (personaje_slug, fecha DESC);
