-- Boss Fight PvP live duels.
-- V23 and V24 are already applied in production; do not renumber this file.

ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS elo_pvp INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS pvp_partidos INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_usuarios_elo_pvp ON usuarios (elo_pvp DESC);

CREATE TABLE IF NOT EXISTS duelos_live (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(20) NOT NULL,
    jugador1_id BIGINT NOT NULL,
    jugador2_id BIGINT,
    jugador2_bot BOOLEAN NOT NULL DEFAULT FALSE,
    ganador_id BIGINT,
    abandonador_id BIGINT,
    ronda_actual INTEGER NOT NULL DEFAULT 0,
    score_jugador1 INTEGER NOT NULL DEFAULT 0,
    score_jugador2 INTEGER NOT NULL DEFAULT 0,
    rondas_validas INTEGER NOT NULL DEFAULT 0,
    jugador1_elo_before INTEGER NOT NULL DEFAULT 1000,
    jugador2_elo_before INTEGER NOT NULL DEFAULT 1000,
    jugador1_elo_after INTEGER,
    jugador2_elo_after INTEGER,
    jugador1_ip VARCHAR(64),
    jugador2_ip VARCHAR(64),
    creado_en TIMESTAMP NOT NULL,
    matched_en TIMESTAMP,
    started_en TIMESTAMP,
    finished_en TIMESTAMP,
    abandoned_en TIMESTAMP,
    last_seen_jugador1 TIMESTAMP,
    last_seen_jugador2 TIMESTAMP,
    CONSTRAINT fk_duelos_live_jugador1 FOREIGN KEY (jugador1_id) REFERENCES usuarios (id),
    CONSTRAINT fk_duelos_live_jugador2 FOREIGN KEY (jugador2_id) REFERENCES usuarios (id),
    CONSTRAINT fk_duelos_live_ganador FOREIGN KEY (ganador_id) REFERENCES usuarios (id),
    CONSTRAINT fk_duelos_live_abandonador FOREIGN KEY (abandonador_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_duelos_live_estado ON duelos_live (estado);
CREATE INDEX IF NOT EXISTS idx_duelos_live_jugador1 ON duelos_live (jugador1_id);
CREATE INDEX IF NOT EXISTS idx_duelos_live_jugador2 ON duelos_live (jugador2_id);
CREATE INDEX IF NOT EXISTS idx_duelos_live_creado ON duelos_live (creado_en);
CREATE INDEX IF NOT EXISTS idx_duelos_live_finished ON duelos_live (finished_en);

CREATE TABLE IF NOT EXISTS duelos_live_rondas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duelo_id BIGINT NOT NULL,
    numero INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL,
    personaje_a_id BIGINT NOT NULL,
    personaje_b_id BIGINT NOT NULL,
    abre_en TIMESTAMP NOT NULL,
    cierra_en TIMESTAMP NOT NULL,
    voto_jugador1 VARCHAR(1),
    voto_jugador2 VARCHAR(1),
    voto_jugador1_en TIMESTAMP,
    voto_jugador2_en TIMESTAMP,
    eleccion_correcta VARCHAR(8),
    jugador1_acerto BOOLEAN,
    jugador2_acerto BOOLEAN,
    decision_ms BIGINT,
    cerrada_en TIMESTAMP,
    CONSTRAINT fk_duelos_live_ronda_duelo FOREIGN KEY (duelo_id) REFERENCES duelos_live (id) ON DELETE CASCADE,
    CONSTRAINT fk_duelos_live_ronda_personaje_a FOREIGN KEY (personaje_a_id) REFERENCES personajes (id),
    CONSTRAINT fk_duelos_live_ronda_personaje_b FOREIGN KEY (personaje_b_id) REFERENCES personajes (id),
    CONSTRAINT uk_duelos_live_ronda_numero UNIQUE (duelo_id, numero)
);

CREATE INDEX IF NOT EXISTS idx_duelos_live_rondas_duelo ON duelos_live_rondas (duelo_id, numero);
CREATE INDEX IF NOT EXISTS idx_duelos_live_rondas_estado ON duelos_live_rondas (estado);
CREATE INDEX IF NOT EXISTS idx_duelos_live_rondas_cierra ON duelos_live_rondas (cierra_en);

INSERT INTO logros (codigo, nombre, descripcion, icono, rareza)
SELECT 'primera_victoria_pvp',
       'Primera victoria PvP',
       'Gana tu primer duelo 1v1 en directo contra otro jugador o contra el bot.',
       'Swords',
       3
WHERE NOT EXISTS (SELECT 1 FROM logros WHERE codigo = 'primera_victoria_pvp');
