-- ===========================================================================
-- V2__email_verification.sql
-- Plan v2 §2.4 — verificación obligatoria de email tras registro.
--
-- Decisión "estricto": un usuario PENDIENTE puede navegar y leer pero NO
-- puede votar ni crear torneos hasta que confirme el email vía link
-- /verify?token=XXX (TTL 24h).
--
-- Nuevos elementos:
--   1. usuarios.estado_verificacion (PENDIENTE|ACTIVO). Por defecto y en
--      filas existentes: ACTIVO — los usuarios actuales no son penalizados
--      retroactivamente. Solo los nuevos registros nacerán PENDIENTE.
--   2. tabla email_verifications con tokens UUID y expiración.
-- ===========================================================================

ALTER TABLE usuarios
    ADD COLUMN estado_verificacion VARCHAR(20) NOT NULL DEFAULT 'ACTIVO';

-- Después del default, los nuevos INSERTs (vía AuthController.registro)
-- pasarán explícitamente 'PENDIENTE' desde Java. El default ACTIVO solo
-- sirve para no romper a usuarios pre-existentes ni a los tests que crean
-- usuarios sin pasar por el flujo de registro.

CREATE TABLE email_verifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    token       VARCHAR(64)  NOT NULL,
    creado_en   TIMESTAMP    NOT NULL,
    expira_en   TIMESTAMP    NOT NULL,
    usado_en    TIMESTAMP,
    CONSTRAINT uk_email_verif_token UNIQUE (token),
    CONSTRAINT fk_email_verif_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
CREATE INDEX idx_email_verif_usuario ON email_verifications (usuario_id);
CREATE INDEX idx_email_verif_expira  ON email_verifications (expira_en);
