-- ===========================================================================
-- V36__cartas_coleccionables.sql
-- Ola 1 — Cartas coleccionables (Fase 1): sistema base server-authoritative
-- de cartas + moneda blanda.
--
-- Bucle de juego F1:
--   jugar (votar / misión diaria / torneo / duelo) → ganar MONEDA →
--   gastar moneda en un SOBRE → abrir sobre → obtener una carta SSR según
--   probabilidades TRANSPARENTES.
--
-- Decisiones del owner reflejadas en el schema:
--   * 1 carta normal por personaje, rareza SSR. La rareza ESPECIAL queda
--     soportada en el modelo (arte curado por el owner) con un flag de
--     curaduría, pero NO se siembra ni entra en el drop normal en F1 —
--     es premio/evento que se revelará en F2.
--   * El catálogo `carta` NO se siembra aquí (los personajes se importan en
--     runtime vía DataSeeder desde personajes-seed.json, no existen en tiempo
--     de migración). CartaCatalogoService crea 1 carta SSR por personaje en
--     cada arranque, idempotente.
--   * Anti-casino: la moneda se gana JUGANDO, jamás con dinero real. Cada
--     movimiento de saldo queda en `monedero_movimiento` (ledger fuente de
--     verdad) y en el audit_log. El UNIQUE(motivo, referencia) da idempotencia
--     a los drops; el índice por (usuario, fecha) soporta el tope diario.
--
-- Portable Postgres + H2 (MODE=PostgreSQL para tests, ddl-auto=validate):
-- BIGINT GENERATED BY DEFAULT AS IDENTITY, BOOLEAN, CHECK y FK ON DELETE
-- CASCADE funcionan en ambos motores.
-- ===========================================================================

-- ─── Catálogo de cartas ────────────────────────────────────────────────────
CREATE TABLE carta (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id    BIGINT       NOT NULL,
    rareza          VARCHAR(16)  NOT NULL,
    especial_curada BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_carta_personaje
        FOREIGN KEY (personaje_id) REFERENCES personajes (id) ON DELETE CASCADE,
    -- Una carta por (personaje, rareza): permite que un personaje tenga su SSR
    -- normal y, en el futuro, una ESPECIAL curada sin duplicar la SSR.
    CONSTRAINT uk_carta_personaje_rareza UNIQUE (personaje_id, rareza),
    CONSTRAINT ck_carta_rareza CHECK (rareza IN ('SSR', 'ESPECIAL'))
);
CREATE INDEX idx_carta_rareza ON carta (rareza);

-- ─── Colección por usuario (server-authoritative) ──────────────────────────
CREATE TABLE usuario_carta (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT     NOT NULL,
    carta_id       BIGINT     NOT NULL,
    cantidad       INTEGER    NOT NULL DEFAULT 1,
    obtenida_en    TIMESTAMP  NOT NULL,
    actualizada_en TIMESTAMP  NOT NULL,
    CONSTRAINT fk_usuario_carta_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_carta_carta
        FOREIGN KEY (carta_id) REFERENCES carta (id) ON DELETE CASCADE,
    -- Una fila por (usuario, carta); los duplicados incrementan `cantidad`.
    CONSTRAINT uk_usuario_carta UNIQUE (usuario_id, carta_id),
    CONSTRAINT ck_usuario_carta_cantidad CHECK (cantidad >= 1)
);
CREATE INDEX idx_usuario_carta_usuario ON usuario_carta (usuario_id);

-- ─── Monedero: saldo de moneda blanda por usuario ──────────────────────────
CREATE TABLE monedero (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT    NOT NULL,
    saldo          BIGINT    NOT NULL DEFAULT 0,
    actualizado_en TIMESTAMP NOT NULL,
    CONSTRAINT fk_monedero_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_monedero_usuario UNIQUE (usuario_id),
    CONSTRAINT ck_monedero_saldo CHECK (saldo >= 0)
);

-- ─── Ledger de movimientos de moneda (fuente de verdad) ─────────────────────
CREATE TABLE monedero_movimiento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id       BIGINT       NOT NULL,
    delta            BIGINT       NOT NULL,
    motivo           VARCHAR(32)  NOT NULL,
    referencia       VARCHAR(96)  NOT NULL,
    saldo_resultante BIGINT       NOT NULL,
    creado_en        TIMESTAMP    NOT NULL,
    CONSTRAINT fk_mon_mov_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    -- Idempotencia de los drops/compras: un mismo (usuario, motivo, referencia)
    -- sólo puede acreditar/debitar una vez. Ej. referencia "dia:2026-05-30"
    -- para la misión diaria, "duelo:123" para un duelo, "voto:50" para un hito.
    CONSTRAINT uk_mon_mov_idem UNIQUE (usuario_id, motivo, referencia)
);
-- Soporta el conteo del tope diario de drops (movimientos del usuario por día).
CREATE INDEX idx_mon_mov_usuario_fecha ON monedero_movimiento (usuario_id, creado_en);
