-- ===========================================================================
-- V3__audit_log.sql
-- Plan v2 §2.6 — audit log persistente de eventos de auth.
--
-- Cada login, registro, cambio de password, etc. deja una fila aquí con
-- contexto suficiente para reconstruir actividad sospechosa:
--   - timestamp + ip_addr para correlación temporal y geográfica.
--   - user_agent para detectar accesos desde dispositivos nuevos.
--   - detalles JSON (TEXT por portabilidad H2/Postgres; si en el futuro
--     queremos queries por contenido migramos a JSONB con un V{n} nuevo).
--
-- usuario_id es nullable porque hay eventos pre-login (LOGIN_FAIL con
-- credenciales inválidas para username inexistente, etc).
-- ===========================================================================

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 'ts' en lugar de 'timestamp' porque TIMESTAMP es palabra reservada
    -- en ANSI SQL y exige quoting en algunos drivers. Más simple cambiar
    -- el nombre que pelearse con escapes.
    ts          TIMESTAMP    NOT NULL,
    usuario_id  BIGINT,
    evento      VARCHAR(50)  NOT NULL,
    detalles    TEXT,
    ip_addr     VARCHAR(64),
    user_agent  VARCHAR(500),
    CONSTRAINT fk_audit_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
);
CREATE INDEX idx_audit_ts      ON audit_log (ts);
CREATE INDEX idx_audit_usuario ON audit_log (usuario_id);
CREATE INDEX idx_audit_evento  ON audit_log (evento);
