CREATE TABLE tier_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    anime_slug VARCHAR(120),
    publico BOOLEAN NOT NULL DEFAULT FALSE,
    slug VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tier_list_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT uk_tier_list_slug UNIQUE (slug)
);

CREATE INDEX idx_tier_list_usuario ON tier_list (usuario_id);
CREATE INDEX idx_tier_list_publico_slug ON tier_list (publico, slug);

CREATE TABLE tier_list_item (
    tier_list_id BIGINT NOT NULL,
    personaje_id BIGINT NOT NULL,
    tier VARCHAR(16) NOT NULL,
    posicion INTEGER NOT NULL,
    PRIMARY KEY (tier_list_id, personaje_id),
    CONSTRAINT fk_tier_item_list FOREIGN KEY (tier_list_id) REFERENCES tier_list(id) ON DELETE CASCADE,
    CONSTRAINT fk_tier_item_personaje FOREIGN KEY (personaje_id) REFERENCES personajes(id) ON DELETE CASCADE
);

CREATE INDEX idx_tier_list_item_orden ON tier_list_item (tier_list_id, tier, posicion);
