-- ===========================================================================
-- V44__cartas_fase_2.sql
-- Cartas Fase 2: sobres de 5 cartas, especiales curadas, pity e idempotencia.
-- Portable Postgres + H2.
-- ===========================================================================

ALTER TABLE carta ADD COLUMN variante VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE carta ADD COLUMN arte_url VARCHAR(500);

ALTER TABLE carta DROP CONSTRAINT uk_carta_personaje_rareza;
ALTER TABLE carta ADD CONSTRAINT uk_carta_personaje_rareza_variante
    UNIQUE (personaje_id, rareza, variante);

CREATE TABLE usuario_carta_pity (
    usuario_id           BIGINT    PRIMARY KEY,
    sobres_sin_especial INTEGER   NOT NULL DEFAULT 0,
    actualizado_en       TIMESTAMP NOT NULL,
    CONSTRAINT fk_usuario_carta_pity_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_usuario_carta_pity_sobres CHECK (sobres_sin_especial >= 0)
);

CREATE TABLE sobre_apertura (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT      NOT NULL,
    idempotency_key     VARCHAR(96) NOT NULL,
    precio              BIGINT      NOT NULL,
    saldo_restante      BIGINT      NOT NULL,
    especial            BOOLEAN     NOT NULL DEFAULT FALSE,
    pity_antes          INTEGER     NOT NULL DEFAULT 0,
    pity_despues        INTEGER     NOT NULL DEFAULT 0,
    monedas_duplicados  BIGINT      NOT NULL DEFAULT 0,
    creado_en           TIMESTAMP   NOT NULL,
    CONSTRAINT fk_sobre_apertura_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_sobre_apertura_idem UNIQUE (usuario_id, idempotency_key),
    CONSTRAINT ck_sobre_apertura_precio CHECK (precio > 0),
    CONSTRAINT ck_sobre_apertura_pity CHECK (pity_antes >= 0 AND pity_despues >= 0)
);
CREATE INDEX idx_sobre_apertura_usuario_fecha ON sobre_apertura (usuario_id, creado_en);

CREATE TABLE sobre_apertura_item (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sobre_apertura_id    BIGINT      NOT NULL,
    carta_id             BIGINT      NOT NULL,
    posicion             INTEGER     NOT NULL,
    nueva                BOOLEAN     NOT NULL,
    recompensa_duplicado BIGINT      NOT NULL DEFAULT 0,
    climax               VARCHAR(16) NOT NULL,
    CONSTRAINT fk_sobre_item_sobre
        FOREIGN KEY (sobre_apertura_id) REFERENCES sobre_apertura (id) ON DELETE CASCADE,
    CONSTRAINT fk_sobre_item_carta
        FOREIGN KEY (carta_id) REFERENCES carta (id) ON DELETE CASCADE,
    CONSTRAINT uk_sobre_item_posicion UNIQUE (sobre_apertura_id, posicion),
    CONSTRAINT ck_sobre_item_posicion CHECK (posicion BETWEEN 1 AND 5),
    CONSTRAINT ck_sobre_item_climax CHECK (climax IN ('NORMAL', 'TOP', 'ESPECIAL')),
    CONSTRAINT ck_sobre_item_recompensa CHECK (recompensa_duplicado >= 0)
);
