CREATE TABLE fantasy_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    semana_iso VARCHAR(8) NOT NULL,
    locked_at TIMESTAMP NULL,
    puntos INTEGER NOT NULL DEFAULT 0,
    puntos_calculados_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fantasy_equipo_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT uk_fantasy_equipo_usuario_semana
        UNIQUE (usuario_id, semana_iso)
);

CREATE INDEX idx_fantasy_equipo_semana_puntos
    ON fantasy_equipo (semana_iso, puntos DESC);

CREATE TABLE fantasy_equipo_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fantasy_equipo_id BIGINT NOT NULL,
    personaje_id BIGINT NOT NULL,
    coste INTEGER NOT NULL,
    CONSTRAINT fk_fantasy_item_equipo
        FOREIGN KEY (fantasy_equipo_id) REFERENCES fantasy_equipo(id) ON DELETE CASCADE,
    CONSTRAINT fk_fantasy_item_personaje
        FOREIGN KEY (personaje_id) REFERENCES personajes(id),
    CONSTRAINT uk_fantasy_item_equipo_personaje
        UNIQUE (fantasy_equipo_id, personaje_id)
);

CREATE INDEX idx_fantasy_item_equipo
    ON fantasy_equipo_item (fantasy_equipo_id);

CREATE INDEX idx_fantasy_item_personaje
    ON fantasy_equipo_item (personaje_id);
