-- ===========================================================================
-- V4__email_failed_queue.sql
-- Plan v2 §2.12 — dead letter queue para emails que no llegaron a Resend
-- tras los reintentos.
--
-- Cuando @Retryable agota sus 3 intentos con backoff exponencial, el
-- @Recover de EmailService persiste aquí el contenido + error_msg para
-- diagnóstico posterior. Un admin puede listar los fallos vía
-- GET /api/admin/email-failures y reintentar manualmente si Resend ya
-- está sano.
--
-- Por qué tabla y no log:
--   - El log se pierde tras la rotación.
--   - Tener el contenido permite reenvio manual (importante para reset
--     password y verify links — el usuario espera ese correo).
--   - Métrica simple: count(*) en esta tabla = severidad del incidente.
-- ===========================================================================

CREATE TABLE email_failed_queue (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            TIMESTAMP    NOT NULL,
    destinatario  VARCHAR(255) NOT NULL,
    asunto        VARCHAR(500) NOT NULL,
    contenido     TEXT         NOT NULL,
    error_msg     VARCHAR(1000),
    -- Tipo del email (RESET_PASSWORD, VERIFICACION, OTROS) para que el
    -- admin pueda priorizar reenvios — los resets de password son los
    -- más sensibles porque el usuario está bloqueado esperando.
    tipo          VARCHAR(50)  NOT NULL,
    reintentado   BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_email_failed_ts   ON email_failed_queue (ts);
CREATE INDEX idx_email_failed_tipo ON email_failed_queue (tipo);
