CREATE TABLE eventos_tematicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    descripcion_corta VARCHAR(500) NOT NULL,
    filtro_kind VARCHAR(20) NOT NULL,
    filtro_valor TEXT NOT NULL,
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT 'amber',
    emoji VARCHAR(16) NOT NULL DEFAULT '*',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    cup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    cup_size INTEGER NOT NULL DEFAULT 8,
    cup_nombre VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_eventos_tematicos_slug UNIQUE (slug),
    CONSTRAINT chk_eventos_tematicos_filtro
        CHECK (filtro_kind IN ('ANIME', 'ANIMES', 'SLUGS')),
    CONSTRAINT chk_eventos_tematicos_cup_size
        CHECK (cup_size IN (8, 16)),
    CONSTRAINT chk_eventos_tematicos_ventana
        CHECK (fin > inicio)
);

CREATE INDEX idx_eventos_tematicos_estado
    ON eventos_tematicos (activo, inicio, fin);

CREATE INDEX idx_eventos_tematicos_cup
    ON eventos_tematicos (activo, cup_enabled, inicio, fin);

ALTER TABLE torneos ADD COLUMN auto_generado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE torneos ADD COLUMN evento_slug VARCHAR(80);
ALTER TABLE torneos ADD COLUMN auto_origen VARCHAR(80);

CREATE INDEX idx_torneos_auto_reciente
    ON torneos (auto_generado, fecha_creacion DESC);

CREATE INDEX idx_torneos_evento_slug
    ON torneos (evento_slug);

INSERT INTO eventos_tematicos (
    slug, titulo, descripcion_corta, filtro_kind, filtro_valor,
    inicio, fin, color, emoji, cup_enabled, cup_size, cup_nombre
) VALUES
(
    'arco-husbandos',
    'Arco Husbandos',
    'Los personajes masculinos mas adorados de la fandom',
    'SLUGS',
    'luffy,zoro,sanji,sasuke,itachi,kakashi,vegeta,shoto_todoroki,hawks,rengoku,satoru_gojo,kento_nanami,megumi_fushiguro,toji_fushiguro,levi_ackerman,light_yagami,lelouch_lamperouge,roy_mustang',
    TIMESTAMP '2026-05-25 00:00:00',
    TIMESTAMP '2026-06-01 23:59:59',
    'violet',
    '🗡️',
    TRUE,
    8,
    'Copa Husbandos'
),
(
    'copa-villanos',
    'Copa Villanos',
    'Los antagonistas mas temidos del anime cara a cara',
    'SLUGS',
    'madara,obito_uchiha,pain,nagato,orochimaru,frieza,cell,tomura_shigaraki,dabi,toga,sosuke_aizen,muzan,akaza,kokushibo,sukuna,toji_fushiguro,mahito,light_yagami,lust,pride,wrath_king_bradley,gasai_yuno,makima,ainz_ooal_gown',
    TIMESTAMP '2026-05-18 00:00:00',
    TIMESTAMP '2026-05-25 23:59:59',
    'rose',
    '😈',
    TRUE,
    8,
    'Copa Villanos'
),
(
    'semana-one-piece',
    'Semana de One Piece',
    'Los Sombrero de Paja conquistan AnimeShowdown',
    'ANIME',
    'One Piece',
    TIMESTAMP '2026-05-13 00:00:00',
    TIMESTAMP '2026-05-20 23:59:59',
    'amber',
    '🏴‍☠️',
    TRUE,
    8,
    'Copa One Piece'
),
(
    'top-waifus',
    'Top Waifus',
    'Las personajes femeninas mas iconicas del anime',
    'SLUGS',
    'nami,nico_robin,hinata,sakura_haruno,toga,nezuko,shinobu,nobara_kugisaki,mikasa_ackerman,rem,rem_and_ram,emilia,saber,riza_hawkeye,olivier_armstrong,lust,asuka,taiga_aisaka,gasai_yuno,rei,mai_sakurajima,asuna,zero_two,makima,megumin,aqua',
    TIMESTAMP '2026-05-05 00:00:00',
    TIMESTAMP '2026-05-12 23:59:59',
    'pink',
    '💖',
    TRUE,
    8,
    'Copa Waifus'
);
