-- ===========================================================================
-- V54__cartas_f3_trading_showcase.sql
-- Cartas F3: trading server-authoritative y showcases sociales.
-- Portable Postgres + H2.
-- ===========================================================================

CREATE TABLE carta_trade (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_id      BIGINT      NOT NULL,
    destinatario_id     BIGINT      NOT NULL,
    carta_ofrecida_id   BIGINT      NOT NULL,
    carta_solicitada_id BIGINT      NOT NULL,
    estado              VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    idempotency_key     VARCHAR(96),
    creado_en           TIMESTAMP   NOT NULL,
    actualizado_en      TIMESTAMP   NOT NULL,
    respondido_en       TIMESTAMP,
    CONSTRAINT fk_carta_trade_solicitante
        FOREIGN KEY (solicitante_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_carta_trade_destinatario
        FOREIGN KEY (destinatario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_carta_trade_ofrecida
        FOREIGN KEY (carta_ofrecida_id) REFERENCES carta (id) ON DELETE CASCADE,
    CONSTRAINT fk_carta_trade_solicitada
        FOREIGN KEY (carta_solicitada_id) REFERENCES carta (id) ON DELETE CASCADE,
    CONSTRAINT ck_carta_trade_estado
        CHECK (estado IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_carta_trade_usuarios CHECK (solicitante_id <> destinatario_id),
    CONSTRAINT ck_carta_trade_cartas CHECK (carta_ofrecida_id <> carta_solicitada_id),
    CONSTRAINT uk_carta_trade_idem UNIQUE (solicitante_id, idempotency_key)
);
CREATE INDEX idx_carta_trade_solicitante ON carta_trade (solicitante_id, creado_en);
CREATE INDEX idx_carta_trade_destinatario ON carta_trade (destinatario_id, creado_en);
CREATE INDEX idx_carta_trade_estado ON carta_trade (estado, creado_en);

CREATE TABLE usuario_carta_showcase (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT      NOT NULL,
    carta_id       BIGINT      NOT NULL,
    slot           VARCHAR(32) NOT NULL,
    creado_en      TIMESTAMP   NOT NULL,
    actualizado_en TIMESTAMP   NOT NULL,
    CONSTRAINT fk_carta_showcase_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_carta_showcase_carta
        FOREIGN KEY (carta_id) REFERENCES carta (id) ON DELETE CASCADE,
    CONSTRAINT uk_carta_showcase_usuario_slot UNIQUE (usuario_id, slot),
    CONSTRAINT ck_carta_showcase_slot
        CHECK (slot IN ('PERFIL', 'DUEL_SKIN', 'SALON_1', 'SALON_2', 'SALON_3'))
);
CREATE INDEX idx_carta_showcase_usuario ON usuario_carta_showcase (usuario_id);
CREATE INDEX idx_carta_showcase_slot ON usuario_carta_showcase (slot, actualizado_en);
