-- ===========================================================================
-- V59__sugerencias_personaje.sql
-- Cola moderada de sugerencias de personaje propuestas por usuarios.
--
-- El usuario logueado propone un personaje (nombre, anime, identidad real
-- exigida por REGLA #7, motivo opcional, URL de referencia). Cada sugerencia
-- entra como PENDIENTE y un admin la aprueba o rechaza con motivo. La sugerencia
-- NO crea un personaje automáticamente — el alta real (con arte/slug/catálogo)
-- la hace el owner manualmente; APROBADO es solo la señal de intención.
--
-- Identidades: BIGINT GENERATED BY DEFAULT AS IDENTITY (estándar SQL, H2+PG).
-- ===========================================================================

CREATE TABLE sugerencias_personaje (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT       NOT NULL,
    nombre          VARCHAR(120) NOT NULL,
    anime           VARCHAR(120) NOT NULL,
    motivo          TEXT,
    identidad       VARCHAR(300) NOT NULL,
    url_referencia  VARCHAR(500),
    estado          VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    motivo_rechazo  VARCHAR(500),
    creado_en       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revisado_en     TIMESTAMP,
    CONSTRAINT fk_sugerencia_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

-- Cola admin FIFO por estado, e historial del proponente.
CREATE INDEX idx_sugerencia_estado_creado ON sugerencias_personaje (estado, creado_en);
CREATE INDEX idx_sugerencia_usuario_creado ON sugerencias_personaje (usuario_id, creado_en);

-- Bucket atómico de rate limit por usuario y hora (mismo patrón que
-- comentario_rate_limit en V56): evita count-then-insert bajo concurrencia.
CREATE TABLE sugerencia_rate_limit (
    usuario_id      BIGINT    NOT NULL,
    ventana_inicio  TIMESTAMP NOT NULL,
    usados          INTEGER   NOT NULL DEFAULT 0,
    actualizado_en  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usuario_id, ventana_inicio),
    CONSTRAINT fk_sugerencia_rate_limit_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE INDEX idx_sugerencia_rate_limit_actualizado
    ON sugerencia_rate_limit (actualizado_en);
