-- ===========================================================================
-- V5__totp_2fa.sql
-- Plan v2 §2.3 — 2FA TOTP (Time-based One-Time Password) opcional por usuario.
--
-- Flujo de activación:
--   1. POST /api/auth/2fa/setup genera secret base32 + lo persiste en
--      usuarios.totp_secret_pendiente (cifrado AES) y devuelve QR/otpauth.
--   2. POST /api/auth/2fa/enable valida {codigo} contra el pendiente y, si
--      coincide, promueve pendiente → activo y setea totp_habilitado=true.
--      Genera además 10 backup codes one-shot.
--   3. POST /api/auth/2fa/disable valida password + código actual y limpia
--      todo (secret + backup codes).
--
-- Flujo de login con 2FA:
--   1. POST /api/auth/login: si password OK + totp_habilitado=true, NO emite
--      JWT/refresh todavía — devuelve {requires2fa:true, challengeToken}.
--      El challengeToken vive en memoria (Caffeine) 60s, 3 intentos máx.
--   2. POST /api/auth/2fa/verify-login con {challengeToken, codigo} (TOTP
--      o backup code). Si OK emite JWT + refresh cookie como login normal.
--
-- Decisiones:
--   - Secret cifrado en BBDD con AES/CBC vía Spring Encryptors (la clave
--     vive en env var TOTP_ENCRYPTION_KEY). Si la BBDD se filtra sin el
--     .env, los secrets son inútiles.
--   - Backup codes hashed con BCrypt (igual que passwords) — son one-shot:
--     al usar uno se marca usado_en y queda inutilizable.
--   - totp_secret_pendiente separado de totp_secret para que un setup a
--     medias (qr escaneado pero código nunca verificado) no rompa el 2FA
--     ya activo del usuario.
-- ===========================================================================

-- Cada ALTER TABLE separado porque H2 (usado en tests con MODE=PostgreSQL) no
-- soporta múltiples ADD COLUMN encadenados con comas — solo Postgres puro
-- los acepta. Mantener portable cuesta cuatro líneas más.

-- Secret TOTP activo. NULL = el usuario no tiene 2FA activado. Cifrado AES.
ALTER TABLE usuarios ADD COLUMN totp_secret VARCHAR(255);

-- Secret pendiente de verificar (escaneado del QR pero código no enviado).
-- Se descarta si no se confirma con /2fa/enable. Cifrado AES.
ALTER TABLE usuarios ADD COLUMN totp_secret_pendiente VARCHAR(255);

-- Flag explícito para no depender de "secret != null". Si en el futuro
-- queremos dejar el secret vivo pero pausar 2FA temporalmente (locked
-- recovery flow), este boolean lo permite sin perder el secret.
ALTER TABLE usuarios ADD COLUMN totp_habilitado BOOLEAN NOT NULL DEFAULT FALSE;

-- Cuándo se activó por primera vez. Solo informativo (UI puede mostrar
-- "2FA activo desde 12 de marzo"). Null = nunca activado.
ALTER TABLE usuarios ADD COLUMN totp_habilitado_en TIMESTAMP;


-- backup codes (Plan v2 §2.3 extendido) -----------------------------------
-- Códigos de recuperación one-shot. Se generan en lote de 10 al activar 2FA
-- y se le devuelven al usuario UNA vez en plaintext (para que los guarde).
-- En BBDD solo viven hasheados con BCrypt — no se pueden recuperar después.
-- Al usar uno, se marca usado_en y deja de servir.
--
-- Cuando los 10 se gastan o caducan, el user puede regenerar set nuevo (eso
-- invalida los anteriores). Endpoint dedicado en bloques futuros.
CREATE TABLE totp_backup_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    codigo_hash VARCHAR(255) NOT NULL,
    creado_en   TIMESTAMP    NOT NULL,
    usado_en    TIMESTAMP,
    CONSTRAINT fk_backup_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
CREATE INDEX idx_backup_usuario ON totp_backup_codes (usuario_id);
CREATE INDEX idx_backup_usuario_usado ON totp_backup_codes (usuario_id, usado_en);
