-- V63__eventos_tematicos_runtime.sql
-- Runtime de eventos tematicos y cups auto-generadas.
-- Sin seed inicial: el catalogo vigente se carga por admin/runtime para no
-- fijar ventanas de producto caducadas en una migracion historica.

CREATE TABLE eventos_tematicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    descripcion_corta VARCHAR(500) NOT NULL,
    filtro_kind VARCHAR(20) NOT NULL,
    filtro_valor TEXT NOT NULL,
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT 'amber',
    emoji VARCHAR(16) NOT NULL DEFAULT '*',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    cup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    cup_size INTEGER NOT NULL DEFAULT 8,
    cup_nombre VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_eventos_tematicos_slug UNIQUE (slug),
    CONSTRAINT chk_eventos_tematicos_filtro
        CHECK (filtro_kind IN ('ANIME', 'ANIMES', 'SLUGS')),
    CONSTRAINT chk_eventos_tematicos_cup_size
        CHECK (cup_size IN (8, 16)),
    CONSTRAINT chk_eventos_tematicos_ventana
        CHECK (fin > inicio)
);

CREATE INDEX idx_eventos_tematicos_estado
    ON eventos_tematicos (activo, inicio, fin);

CREATE INDEX idx_eventos_tematicos_cup
    ON eventos_tematicos (activo, cup_enabled, inicio, fin);

ALTER TABLE torneos ADD COLUMN auto_generado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE torneos ADD COLUMN evento_slug VARCHAR(80);
ALTER TABLE torneos ADD COLUMN auto_origen VARCHAR(80);

CREATE INDEX idx_torneos_auto_reciente
    ON torneos (auto_generado, fecha_creacion DESC);

CREATE INDEX idx_torneos_evento_slug
    ON torneos (evento_slug);
