-- V65: recompensas exclusivas de copa de evento.
-- Al finalizar una copa con evento_slug, se reparte a TODOS los que predijeron
-- en ella: moneda + carta especial exclusiva + insignia + credito de sobre gratis.
-- La config vive en el propio evento (runtime/admin, como V63); el reparto es
-- idempotente por (torneo, usuario) via evento_recompensa_entregada.

ALTER TABLE eventos_tematicos ADD COLUMN recompensa_moneda INTEGER NOT NULL DEFAULT 0;
ALTER TABLE eventos_tematicos ADD COLUMN recompensa_carta_especial_slug VARCHAR(120);
ALTER TABLE eventos_tematicos ADD COLUMN recompensa_badge_codigo VARCHAR(80);
ALTER TABLE eventos_tematicos ADD COLUMN recompensa_sobre_gratis BOOLEAN NOT NULL DEFAULT FALSE;

-- Ledger del reparto: una fila por (torneo, usuario) premiado. El UNIQUE hace
-- idempotente el finalize aunque el scheduler vuelva a dispararlo.
CREATE TABLE evento_recompensa_entregada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    evento_slug VARCHAR(80) NOT NULL,
    moneda INTEGER NOT NULL DEFAULT 0,
    carta_especial_id BIGINT,
    badge_codigo VARCHAR(80),
    sobre_gratis BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evento_recompensa_torneo_usuario UNIQUE (torneo_id, usuario_id)
);

CREATE INDEX idx_evento_recompensa_usuario
    ON evento_recompensa_entregada (usuario_id, created_at DESC);

-- Creditos de sobre gratis (el "sobre tematico" se abre cuando el usuario vuelve).
-- referencia UNIQUE = idempotencia del otorgamiento; consumido_en NULL = pendiente.
CREATE TABLE sobre_gratis_credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    origen VARCHAR(80) NOT NULL,
    referencia VARCHAR(160) NOT NULL,
    etiqueta VARCHAR(120),
    consumido_en TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sobre_gratis_referencia UNIQUE (referencia)
);

CREATE INDEX idx_sobre_gratis_pendiente
    ON sobre_gratis_credito (usuario_id, consumido_en);
