-- ===========================================================================
-- V6__notificaciones.sql
-- Plan v2 §2.13 — notificaciones in-app persistentes.
--
-- Cada notificación queda guardada en BBDD para que aparezca en la campanita
-- del header incluso si el usuario no estaba conectado por WebSocket cuando
-- se generó (caso "abro la app al día siguiente"). El push live por WS solo
-- emite eventos en tiempo real al usuario; este modelo da el historial.
--
-- Triggers iniciales conectados (Plan v2 §2.13):
--   - BIENVENIDA tras email verificado.
--   - TORNEO_FINALIZADO al admin que creó el torneo.
--
-- Triggers futuros (hooks listos, conectar cuando llegue su bloque):
--   - BADGE_DESBLOQUEADO (Plan v2 §4.2)
--   - PREDICCION_ACERTADA (§4.4)
--   - SEGUIDOR_NUEVO (§4.5)
--   - REACTION_RECIBIDA (§4.3)
--
-- payload JSONB lo dejamos como TEXT por portabilidad H2/Postgres (igual que
-- audit_log en V3). Migrar a JSONB con un V{n} futuro si necesitamos queries
-- por contenido.
-- ===========================================================================

CREATE TABLE notificaciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL,
    tipo        VARCHAR(50)  NOT NULL,
    titulo      VARCHAR(200) NOT NULL,
    mensaje     VARCHAR(500),
    -- JSON con datos contextuales: ids de entidades referenciadas, urls,
    -- etc. El frontend lo usa para construir links. Ejemplo:
    --   { "torneoId": 42, "torneoSlug": "shonen-spring-2026" }
    payload     TEXT,
    leida       BOOLEAN      NOT NULL DEFAULT FALSE,
    creado_en   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_notif_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

-- Index combinado para el query principal: "dame las no leídas de este
-- usuario, ordenadas por fecha desc". Cubre también el count del badge.
CREATE INDEX idx_notif_usuario_leida_fecha
    ON notificaciones (usuario_id, leida, creado_en DESC);

-- Index secundario para listar todas (leídas + no leídas) del usuario
-- ordenadas. Útil en la página de historial completo.
CREATE INDEX idx_notif_usuario_fecha
    ON notificaciones (usuario_id, creado_en DESC);
