-- ===========================================================================
-- V72__usuario_marco.sql
-- Cosmético coin-sink: marcos de avatar comprables con moneda blanda.
--   usuario_marco        = posesión (qué marcos ha desbloqueado cada usuario).
--   usuarios.marco_avatar = el marco actualmente equipado (NULL = ninguno).
-- El catálogo de marcos (id, precio, estilo) vive en código (MarcoCatalogo),
-- no en BBDD: son finitos y curados, sin panel de admin.
-- Portable Postgres + H2.
-- ===========================================================================

CREATE TABLE usuario_marco (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT      NOT NULL,
    marco_id     VARCHAR(64) NOT NULL,
    adquirido_en TIMESTAMP   NOT NULL,
    CONSTRAINT fk_usuario_marco_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uk_usuario_marco_unico UNIQUE (usuario_id, marco_id)
);
CREATE INDEX idx_usuario_marco_usuario ON usuario_marco (usuario_id);

ALTER TABLE usuarios ADD COLUMN marco_avatar VARCHAR(64);
