-- V78: progreso diario y racha SERVER-SIDE (#1 de la auditoría ultra).
-- Hasta ahora la racha y la misión diaria vivían solo en localStorage: se
-- evaporaban al limpiar el navegador, no cruzaban dispositivos y no permitían
-- notificaciones ni leaderboards. Estas dos tablas mueven la verdad al servidor,
-- con el reloj del servidor como autoridad del día (mismo Clock que el resto del
-- sistema diario: DROP_MISION_DIARIA, cofre diario).

-- Progreso de la misión diaria, una fila por (usuario, día). El UNIQUE es el
-- ancla de idempotencia: un día por usuario, agregando votos/juegos/ranking.
CREATE TABLE daily_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    votos INTEGER NOT NULL DEFAULT 0,
    juegos INTEGER NOT NULL DEFAULT 0,
    ranking_visto BOOLEAN NOT NULL DEFAULT FALSE,
    completado BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMP NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_daily_progress_usuario_fecha UNIQUE (usuario_id, fecha),
    CONSTRAINT fk_daily_progress_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

-- Lecturas típicas: progreso de hoy y ventana de N días recientes por usuario.
CREATE INDEX idx_daily_progress_usuario_fecha ON daily_progress (usuario_id, fecha);

-- Racha denormalizada, una fila por usuario. Se actualiza (con lock) en el
-- momento en que un día pasa a completado. `ultima_fecha_completada` permite
-- decidir en lectura si la racha sigue viva (hoy o ayer) sin recomputarla, y es
-- la base para futuras notificaciones ("tu racha expira en 3h").
CREATE TABLE daily_streak (
    usuario_id BIGINT PRIMARY KEY,
    actual INTEGER NOT NULL DEFAULT 0,
    record INTEGER NOT NULL DEFAULT 0,
    ultima_fecha_completada DATE,
    actualizado_en TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT fk_daily_streak_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);
