-- Dedup de reportes de comentario.
--
-- Antes, reportar un comentario lo ocultaba al instante (PENDIENTE_REVISION) con UN
-- solo reporte, y el mismo usuario podía reportar N veces inflando el contador. Esta
-- tabla registra reportes únicos por (comentario, usuario) con un UNIQUE, de modo que:
--   - un usuario solo puede reportar una vez (el contador refleja reportantes
--     DISTINTOS, no clics);
--   - el cambio a PENDIENTE_REVISION pasa a exigir un umbral de reportes (en el
--     servicio: app.comentarios.reportes-umbral, por defecto 3).
CREATE TABLE reporte_comentario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comentario_id BIGINT    NOT NULL REFERENCES comentarios_personaje(id) ON DELETE CASCADE,
    usuario_id    BIGINT    NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    creado_en     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reporte_comentario UNIQUE (comentario_id, usuario_id)
);

CREATE INDEX idx_reporte_comentario_comentario ON reporte_comentario (comentario_id);
