-- ===========================================================================
-- V7__logros.sql
-- Plan v2 §4.2 — Sistema de badges/logros.
--
-- Dos tablas:
--   logros            catálogo inmutable de badges (id, código, copy, rareza)
--   usuario_logros    join con cuándo se desbloqueó cada uno
--
-- Diseño:
--   - codigo es el identificador estable que usa el código Java para
--     desbloquear (BadgeService.desbloquear("primer_voto", usuario)).
--   - rareza es 1..5 (COMUN, POCO_COMUN, RARO, EPICO, LEGENDARIO) y rige
--     el color del marco en la UI.
--   - icono es el nombre de un icono lucide-react o un emoji literal.
--   - usuario_logros con UNIQUE (usuario_id, logro_id) hace que desbloquear
--     sea idempotente — el segundo INSERT con la misma combinación falla
--     (lo capturamos en el service como "ya desbloqueado, no-op").
--
-- Catálogo inicial de 14 badges del Plan v2 §4.2. Algunos triggers ya
-- conectados (votos, torneo completo), otros pendientes de bloques futuros
-- (predicciones=4.4, daily_streak=8.1, fanboy=15.x). El catálogo queda
-- completo desde V7 para evitar V{n+1} solo de copy nuevo más adelante.
-- ===========================================================================

CREATE TABLE logros (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(64)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  VARCHAR(300) NOT NULL,
    icono        VARCHAR(50)  NOT NULL,
    rareza       SMALLINT     NOT NULL,
    CONSTRAINT uk_logros_codigo UNIQUE (codigo),
    CONSTRAINT ck_logros_rareza CHECK (rareza BETWEEN 1 AND 5)
);

CREATE TABLE usuario_logros (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT     NOT NULL,
    logro_id        BIGINT     NOT NULL,
    desbloqueado_en TIMESTAMP  NOT NULL,
    CONSTRAINT fk_usuario_logros_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_logros_logro
        FOREIGN KEY (logro_id) REFERENCES logros (id),
    CONSTRAINT uk_usuario_logros_par UNIQUE (usuario_id, logro_id)
);
CREATE INDEX idx_usuario_logros_usuario ON usuario_logros (usuario_id);
CREATE INDEX idx_usuario_logros_logro   ON usuario_logros (logro_id);


-- ---------------------------------------------------------------------------
-- Seed del catálogo. 14 badges. Rarezas:
--   1 COMUN       (gris)    — primer hit, accesible en pocas horas
--   2 POCO_COMUN  (verde)   — requiere algo de actividad
--   3 RARO        (azul)    — meses de actividad
--   4 EPICO       (morado)  — top players
--   5 LEGENDARIO  (dorado)  — % de jugadores extremadamente bajo
-- ---------------------------------------------------------------------------

INSERT INTO logros (codigo, nombre, descripcion, icono, rareza) VALUES
    ('primer_voto',
     'Primer voto',
     'Diste tu primer voto en AnimeShowdown.',
     'Vote', 1),

    ('cien_votos',
     'Centenario',
     'Has votado 100 veces. La comunidad nota tu opinión.',
     'TrendingUp', 2),

    ('mil_votos',
     'Mil batallas',
     '1000 votos. Eres parte del corazón de AnimeShowdown.',
     'Crown', 4),

    ('voto_minoritario',
     'Punto de vista único',
     'Votaste por un personaje que solo el 10% eligió.',
     'EyeOff', 3),

    ('predicciones_3_seguidas',
     'Buen ojo',
     'Predijiste correctamente 3 enfrentamientos seguidos.',
     'Target', 2),

    ('predicciones_10_seguidas',
     'Profeta',
     '10 predicciones seguidas acertadas. Eres oráculo.',
     'Sparkles', 4),

    ('torneo_completo',
     'Torneo completo',
     'Votaste en todos los enfrentamientos de un torneo entero.',
     'Trophy', 2),

    ('cazador_villanos',
     'Cazador de villanos',
     'La mayoría de tus votos son a antagonistas. Sabes apreciar el caos.',
     'Skull', 3),

    ('fanboy_anime',
     'Devoto',
     'Más del 30% de tus votos son a personajes del mismo anime.',
     'Heart', 2),

    ('profeta',
     'Oráculo de Delfos',
     '20+ predicciones acertadas en total. Tu intuición no falla.',
     'Eye', 4),

    ('reclutador',
     'Reclutador',
     '5 amigos se registraron usando tu código de referido.',
     'Users', 3),

    ('daily_streak_7',
     'Constancia semanal',
     '7 días consecutivos completando el Daily Challenge.',
     'Flame', 2),

    ('daily_streak_30',
     'Disciplina absoluta',
     '30 días seguidos sin saltar ni un Daily.',
     'Zap', 4),

    ('daily_streak_100',
     'Inmortal',
     '100 días consecutivos. Estás en otro plano.',
     'Star', 5);
