-- #11 — Soporte de eventos por CATEGORÍA en el backend.
--
-- El filtro de eventos 'categoria' (Arco Husbandos / Copa Villanos / Top Waifus)
-- solo existía en el frontend (data/personajes-tags.js); el backend lo rechazaba, así
-- que crear un evento por el panel admin reemplazaba el hardcode y perdía la capacidad
-- de eventos por categoría. Esta tabla porta el mapeo slug→categoría al backend para
-- que participantes() resuelva los eventos de categoría server-side. (El frontend sigue
-- usando su copia para el filtro de visualización y los juegos; unificar la lectura es
-- un follow-up.)
CREATE TABLE personaje_categoria (
    personaje_slug VARCHAR(120) NOT NULL,
    categoria      VARCHAR(40)  NOT NULL,
    CONSTRAINT pk_personaje_categoria PRIMARY KEY (personaje_slug, categoria)
);

CREATE INDEX idx_personaje_categoria_cat ON personaje_categoria (categoria);

INSERT INTO personaje_categoria (personaje_slug, categoria) VALUES
    ('luffy', 'hero'),
    ('luffy', 'protagonist'),
    ('luffy', 'husbando'),
    ('luffy', 'shounen'),
    ('luffy', 'power-scaling'),
    ('zoro', 'rival'),
    ('zoro', 'hero'),
    ('zoro', 'husbando'),
    ('zoro', 'shounen'),
    ('sanji', 'hero'),
    ('sanji', 'husbando'),
    ('sanji', 'shounen'),
    ('nami', 'hero'),
    ('nami', 'waifu'),
    ('nico_robin', 'hero'),
    ('nico_robin', 'waifu'),
    ('edward_newgate', 'mentor'),
    ('naruto', 'hero'),
    ('naruto', 'protagonist'),
    ('naruto', 'shounen'),
    ('naruto', 'power-scaling'),
    ('sasuke', 'rival'),
    ('sasuke', 'antihero'),
    ('sasuke', 'husbando'),
    ('sasuke', 'shounen'),
    ('itachi', 'antihero'),
    ('itachi', 'husbando'),
    ('itachi', 'shounen'),
    ('kakashi', 'mentor'),
    ('kakashi', 'husbando'),
    ('jiraya', 'mentor'),
    ('tsunade', 'mentor'),
    ('madara', 'villain'),
    ('madara', 'power-scaling'),
    ('obito_uchiha', 'villain'),
    ('obito_uchiha', 'antihero'),
    ('pain', 'villain'),
    ('nagato', 'villain'),
    ('nagato', 'antihero'),
    ('orochimaru', 'villain'),
    ('hinata', 'dandere'),
    ('hinata', 'waifu'),
    ('sakura_haruno', 'waifu'),
    ('gaara', 'rival'),
    ('gaara', 'antihero'),
    ('goku', 'hero'),
    ('goku', 'protagonist'),
    ('goku', 'shounen'),
    ('goku', 'power-scaling'),
    ('vegeta', 'rival'),
    ('vegeta', 'antihero'),
    ('vegeta', 'husbando'),
    ('vegeta', 'shounen'),
    ('vegeta', 'power-scaling'),
    ('piccolo', 'mentor'),
    ('frieza', 'villain'),
    ('frieza', 'shounen'),
    ('frieza', 'power-scaling'),
    ('cell', 'villain'),
    ('cell', 'shounen'),
    ('deku', 'hero'),
    ('deku', 'protagonist'),
    ('deku', 'shounen'),
    ('allmight', 'mentor'),
    ('allmight', 'hero'),
    ('allmight', 'shounen'),
    ('bakugo', 'rival'),
    ('bakugo', 'shounen'),
    ('shoto_todoroki', 'rival'),
    ('shoto_todoroki', 'husbando'),
    ('tomura_shigaraki', 'villain'),
    ('dabi', 'villain'),
    ('toga', 'villain'),
    ('toga', 'waifu'),
    ('hawks', 'hero'),
    ('hawks', 'husbando'),
    ('ichigo_kurosaki', 'hero'),
    ('ichigo_kurosaki', 'protagonist'),
    ('ichigo_kurosaki', 'shounen'),
    ('sosuke_aizen', 'villain'),
    ('nezuko', 'waifu'),
    ('nezuko', 'shounen'),
    ('shinobu', 'waifu'),
    ('rengoku', 'mentor'),
    ('rengoku', 'hero'),
    ('rengoku', 'husbando'),
    ('rengoku', 'shounen'),
    ('inosuke', 'rival'),
    ('inosuke', 'shounen'),
    ('zenitsu_agatsuma', 'hero'),
    ('zenitsu_agatsuma', 'shounen'),
    ('muzan', 'villain'),
    ('akaza', 'villain'),
    ('kokushibo', 'villain'),
    ('itadori', 'hero'),
    ('itadori', 'protagonist'),
    ('itadori', 'shounen'),
    ('satoru_gojo', 'mentor'),
    ('satoru_gojo', 'husbando'),
    ('satoru_gojo', 'shounen'),
    ('satoru_gojo', 'power-scaling'),
    ('kento_nanami', 'mentor'),
    ('kento_nanami', 'husbando'),
    ('megumi_fushiguro', 'hero'),
    ('megumi_fushiguro', 'husbando'),
    ('megumi_fushiguro', 'shounen'),
    ('nobara_kugisaki', 'hero'),
    ('nobara_kugisaki', 'waifu'),
    ('nobara_kugisaki', 'shounen'),
    ('sukuna', 'villain'),
    ('sukuna', 'shounen'),
    ('sukuna', 'power-scaling'),
    ('toji_fushiguro', 'villain'),
    ('toji_fushiguro', 'antihero'),
    ('toji_fushiguro', 'husbando'),
    ('mahito', 'villain'),
    ('eren_yeager', 'antihero'),
    ('eren_yeager', 'protagonist'),
    ('mikasa_ackerman', 'kuudere'),
    ('mikasa_ackerman', 'hero'),
    ('mikasa_ackerman', 'waifu'),
    ('levi_ackerman', 'hero'),
    ('levi_ackerman', 'husbando'),
    ('light_yagami', 'villain'),
    ('light_yagami', 'antihero'),
    ('light_yagami', 'protagonist'),
    ('light_yagami', 'husbando'),
    ('lelouch_lamperouge', 'antihero'),
    ('lelouch_lamperouge', 'protagonist'),
    ('lelouch_lamperouge', 'husbando'),
    ('lelouch_lamperouge', 'mecha'),
    ('rem', 'waifu'),
    ('rem', 'isekai'),
    ('rem_and_ram', 'waifu'),
    ('rem_and_ram', 'isekai'),
    ('emilia', 'waifu'),
    ('emilia', 'isekai'),
    ('natsuki_subaru', 'protagonist'),
    ('natsuki_subaru', 'isekai'),
    ('saber', 'waifu'),
    ('saber', 'hero'),
    ('edward_elric', 'hero'),
    ('edward_elric', 'protagonist'),
    ('alphonse_elric', 'hero'),
    ('roy_mustang', 'mentor'),
    ('roy_mustang', 'husbando'),
    ('riza_hawkeye', 'waifu'),
    ('maes_hughes', 'mentor'),
    ('olivier_armstrong', 'waifu'),
    ('van_hohenheim', 'mentor'),
    ('scar', 'antihero'),
    ('lust', 'villain'),
    ('lust', 'waifu'),
    ('pride', 'villain'),
    ('wrath_king_bradley', 'villain'),
    ('flamme', 'mentor'),
    ('fushi', 'protagonist'),
    ('asuka', 'tsundere'),
    ('asuka', 'waifu'),
    ('asuka', 'mecha'),
    ('taiga_aisaka', 'tsundere'),
    ('taiga_aisaka', 'waifu'),
    ('gasai_yuno', 'yandere'),
    ('gasai_yuno', 'villain'),
    ('gasai_yuno', 'waifu'),
    ('rei', 'kuudere'),
    ('rei', 'waifu'),
    ('rei', 'mecha'),
    ('mai_sakurajima', 'waifu'),
    ('asuna', 'waifu'),
    ('zero_two', 'waifu'),
    ('makima', 'villain'),
    ('makima', 'waifu'),
    ('megumin', 'waifu'),
    ('megumin', 'isekai'),
    ('aqua', 'waifu'),
    ('aqua', 'isekai'),
    ('kazuma_satou', 'protagonist'),
    ('kazuma_satou', 'isekai'),
    ('rudeus_greyrat', 'protagonist'),
    ('rudeus_greyrat', 'isekai'),
    ('ainz_ooal_gown', 'villain'),
    ('ainz_ooal_gown', 'isekai'),
    ('shinji_ikari', 'protagonist'),
    ('shinji_ikari', 'mecha'),
    ('koji_kabuto', 'hero'),
    ('koji_kabuto', 'mecha'),
    ('mazinger_z', 'mecha'),
    ('mazinger_z', 'power-scaling'),
    ('simon', 'protagonist'),
    ('simon', 'mecha'),
    ('kamina', 'mentor'),
    ('kamina', 'mecha'),
    ('shoyo_hinata', 'protagonist'),
    ('shoyo_hinata', 'sports-anime'),
    ('tobio_kageyama', 'rival'),
    ('tobio_kageyama', 'sports-anime'),
    ('yoichi_isagi', 'protagonist'),
    ('yoichi_isagi', 'sports-anime'),
    ('rin_itoshi', 'rival'),
    ('rin_itoshi', 'sports-anime'),
    ('mamoru_endou', 'protagonist'),
    ('mamoru_endou', 'sports-anime'),
    ('shuuya_gouenji', 'rival'),
    ('shuuya_gouenji', 'sports-anime'),
    ('saitama', 'hero'),
    ('saitama', 'protagonist'),
    ('saitama', 'power-scaling');

-- Permitir el kind CATEGORIA en eventos_tematicos (antes solo ANIME/ANIMES/SLUGS).
ALTER TABLE eventos_tematicos DROP CONSTRAINT chk_eventos_tematicos_filtro;
ALTER TABLE eventos_tematicos ADD CONSTRAINT chk_eventos_tematicos_filtro
    CHECK (filtro_kind IN ('ANIME', 'ANIMES', 'SLUGS', 'CATEGORIA'));
