-- ===========================================================================
-- V8__reacciones.sql
-- Plan v2 §4.3 — Reactions emoji sobre personajes / torneos / matches.
--
-- 1 reaction por par (usuario, target). Si el usuario clica otro emoji, se
-- cambia el tipo. Si clica el mismo emoji que ya tiene, se borra (toggle off).
-- La lógica vive en ReaccionService — aquí solo garantizamos la unicidad con
-- el UNIQUE constraint.
--
-- target_type es VARCHAR con CHECK (portable entre Postgres y H2 sin tener
-- que crear un tipo ENUM custom). Valores: PERSONAJE, TORNEO, MATCH.
-- En esta fase implementamos PERSONAJE y TORNEO; MATCH queda preparado
-- para una segunda fase si decidimos meter reactions en cada enfrentamiento.
--
-- tipo es VARCHAR(20) con los 4 emojis fijos del plan:
--   FIRE (🔥) — viral / cool
--   HEART (❤️) — me encanta
--   LAUGH (😂) — divertido / payaso
--   CRY (😢) — me pone triste / lo siento por
-- ===========================================================================

CREATE TABLE reacciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT       NOT NULL,
    tipo         VARCHAR(20)  NOT NULL,
    target_type  VARCHAR(20)  NOT NULL,
    target_id    BIGINT       NOT NULL,
    fecha        TIMESTAMP    NOT NULL,
    CONSTRAINT fk_reaccion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_reacciones_tipo
        CHECK (tipo IN ('FIRE', 'HEART', 'LAUGH', 'CRY')),
    CONSTRAINT ck_reacciones_target
        CHECK (target_type IN ('PERSONAJE', 'TORNEO', 'MATCH')),
    -- Un usuario solo puede tener UNA reaccion por target (la del momento).
    -- Para "cambiar" reacciones, el service hace UPDATE en lugar de INSERT.
    CONSTRAINT uk_reacciones_par
        UNIQUE (usuario_id, target_type, target_id)
);

-- Index para agregaciones por target (count GROUP BY tipo): el conteo del
-- ReactionsBar en /personajes/{slug} hace SELECT tipo, COUNT(*) FROM
-- reacciones WHERE target_type=? AND target_id=? GROUP BY tipo.
CREATE INDEX idx_reacciones_target
    ON reacciones (target_type, target_id);

-- Index para "mis reactions" — por si en el futuro queremos mostrar al
-- usuario un historial de "a lo que has reaccionado".
CREATE INDEX idx_reacciones_usuario
    ON reacciones (usuario_id);
