-- ===========================================================================
-- V9__predicciones.sql
-- Plan v2 §4.4 — Predicciones de bracket.
--
-- El usuario predice quién ganará cada enfrentamiento del torneo antes de
-- que se resuelva. Cuando el torneo se finaliza (TorneoService.finalizar),
-- las predicciones se marcan acertada=true/false comparando contra el
-- ganador real de cada match.
--
-- UNIQUE(usuario_id, enfrentamiento_id) → 1 predicción por par. Si el
-- usuario vuelve a predecir el mismo match (mientras no esté resuelto),
-- el service hace UPDATE en lugar de INSERT.
--
-- acertada NULL → predicción aún sin resolver (torneo SCHEDULED/IN_PROGRESS).
-- acertada TRUE/FALSE → ya resuelta al finalizar el torneo.
-- ===========================================================================

CREATE TABLE predicciones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              BIGINT     NOT NULL,
    enfrentamiento_id       BIGINT     NOT NULL,
    personaje_predicho_id   BIGINT     NOT NULL,
    fecha                   TIMESTAMP  NOT NULL,
    -- NULL = pendiente; TRUE/FALSE = resuelta tras finalizar el torneo.
    acertada                BOOLEAN,
    CONSTRAINT fk_pred_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_pred_enf
        FOREIGN KEY (enfrentamiento_id) REFERENCES enfrentamientos (id) ON DELETE CASCADE,
    CONSTRAINT fk_pred_personaje
        FOREIGN KEY (personaje_predicho_id) REFERENCES personajes (id),
    CONSTRAINT uk_pred_usuario_enf UNIQUE (usuario_id, enfrentamiento_id)
);

CREATE INDEX idx_pred_usuario       ON predicciones (usuario_id);
CREATE INDEX idx_pred_enf           ON predicciones (enfrentamiento_id);
-- Para "predicciones acertadas del mes" del leaderboard: filtramos por
-- acertada=true + fecha en rango. Index parcial sería más eficiente en
-- Postgres puro pero H2 no los soporta — usamos compuesto.
CREATE INDEX idx_pred_acertada_fecha ON predicciones (acertada, fecha);
