spring.application.name=animeshowdown

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/animeshowdown_db
spring.datasource.username=animeshowdown_user
spring.datasource.password=animeshowdown_dev_2026

# JPA
spring.jpa.hibernate.ddl-auto=update

# Hibernate SQL logging (solo desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mi_clave_super_secreta_y_muy_larga_para_animeshowdown_2026
jwt.expiration=3600000